# Options
#
[window]
option_as_alt = "Both"
#
###############
# Keybindings
#
# Get the first part (keycode) from:
# https://en.wikipedia.org/wiki/List_of_Unicode_characters
#
# and the second part (modifiers) from:
# https://www.leonerd.org.uk/hacks/fixterms/

## Option + å = '
[[keyboard.bindings]]
chars = "\u001B[39;u"
key = "å"
mods = "Alt"

## Shift + Option + å = "
[[keyboard.bindings]]
chars = "\u001B[34;u"
key = "å"
mods = "Shift|Alt"

## Option + ä
[[keyboard.bindings]]
chars = "\u001B[27;3u"
key = "ä"
mods = "Alt"

## Option + ö
[[keyboard.bindings]]
chars = "\u001B[27;3u"
key = "ö"
mods = "Alt"

## Shift + Enter
[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return" 
mods = "Shift"

## Ctrl + Enter
[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

## Ctrl + /
[[keyboard.bindings]]
chars = "\u001B[47;5u"
key = "/"
mods = "Control"

#
###############
# Font - JetBrainsMono Nerd Font
#
[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"
#
###############
# Theme - Catppuccin
#
[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

###############
