"$schema" = 'https://starship.rs/config-schema.json'

[git_branch]
style = "bold #ab9df2"

[directory]
style = "bold #ffd866"

[git_status]
style = "bold #ff6188"

[character]
success_symbol = '[➜](bold #a9dc76)'
error_symbol = '[➜](bold #ff6188)'
